### ISSUE TITLE
Questions about 'MP-GTF'

### ISSUE THREAD

**Issue by ujscjj** [sp-uhh/mp-gtf#1]
Hi, thank you for your sharing. I have two questions.
1.You have present how to plot the time domain representation.Could you please show me the code about ploting the frequency domain representation?
2.How to multiply the input with filterbank? Can you show the code?
Thank you very much.

**Comment by dditter** [comment]
Hi,
1. Just run `np.abs(np.fft.rfft(filterbank))` and then use 'imshow' as for the time-domain plot.
2. You can use `np.convolve()`for each filter output but you should downsample the output signals. Usally the downsampling factor is chosen to be half of the window size, i.e. a factor of 8.
